begin;

create extension if not exists pgcrypto;

create table if not exists public.campaigns (
  id smallint primary key default 1 check (id = 1),
  active boolean not null default false,
  started_at timestamptz,
  paused_at timestamptz,
  last_send_at timestamptz,
  lead_seed_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  company text not null,
  segment text not null default '',
  city text not null default '',
  uf text not null default '',
  region text not null default '',
  priority text not null default '',
  email text not null default '',
  email_source text not null default '',
  can_send boolean not null default false,
  commercial_profile text not null default '',
  regional_market text not null default '',
  applications text not null default '',
  suggested_products text not null default '',
  differentiation text not null default '',
  personalization_basis text not null default '',
  confidence text not null default '',
  human_review text not null default '',
  subject text not null default '',
  greeting text not null default '',
  initial_body text not null default '',
  followup1_body text not null default '',
  followup2_body text not null default '',
  cta text not null default '',
  privacy_footer text not null default '',
  campaign_status text not null default 'Aguardando aprovação',
  approved boolean not null default false,
  approved_at timestamptz,
  sent_at timestamptz,
  followup1_at timestamptz,
  followup2_at timestamptz,
  response text not null default '',
  response_class text not null default '',
  opted_out boolean not null default false,
  bounce text not null default '',
  notes text not null default '',
  regional_source text not null default '',
  specific_source text not null default '',
  research_prompt text not null default '',
  version text not null default '',
  stage smallint not null default 0 check (stage between 0 and 3),
  replied boolean not null default false,
  paused boolean not null default false,
  dry_run_generated boolean not null default false,
  message_ids jsonb not null default '[]'::jsonb,
  research jsonb,
  source_type text not null default '',
  cnpj text not null default '',
  cnae text not null default '',
  cnae_description text not null default '',
  mx_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists leads_email_unique
  on public.leads (lower(email))
  where email <> '';

create index if not exists leads_campaign_queue_idx
  on public.leads (approved, paused, opted_out, replied, stage, priority, confidence, id);

create index if not exists leads_state_idx
  on public.leads (uf, campaign_status);

create index if not exists leads_cnpj_idx
  on public.leads (cnpj)
  where cnpj <> '';

create table if not exists public.active_clients (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  legal_name text not null default '',
  city text not null default '',
  cnpj text not null default '',
  email text not null default '',
  site text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists active_clients_cnpj_unique
  on public.active_clients (cnpj)
  where cnpj <> '';

create index if not exists active_clients_email_idx
  on public.active_clients (lower(email))
  where email <> '';

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  at timestamptz not null default now(),
  lead_id bigint references public.leads(id) on delete set null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists events_type_at_idx
  on public.events (type, at desc);

create index if not exists events_lead_at_idx
  on public.events (lead_id, at desc);

create table if not exists public.processed_imap_uids (
  mailbox text not null default 'INBOX',
  uid text not null,
  processed_at timestamptz not null default now(),
  primary key (mailbox, uid)
);

create table if not exists public.email_jobs (
  id uuid primary key default gen_random_uuid(),
  lead_id bigint not null references public.leads(id) on delete cascade,
  stage smallint not null check (stage between 0 and 2),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  attempts integer not null default 0,
  message_id text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lead_id, stage)
);

create index if not exists email_jobs_claim_idx
  on public.email_jobs (status, available_at, created_at)
  where status in ('pending', 'failed');

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists campaigns_touch_updated_at on public.campaigns;
create trigger campaigns_touch_updated_at
before update on public.campaigns
for each row execute function public.touch_updated_at();

drop trigger if exists leads_touch_updated_at on public.leads;
create trigger leads_touch_updated_at
before update on public.leads
for each row execute function public.touch_updated_at();

drop trigger if exists active_clients_touch_updated_at on public.active_clients;
create trigger active_clients_touch_updated_at
before update on public.active_clients
for each row execute function public.touch_updated_at();

drop trigger if exists email_jobs_touch_updated_at on public.email_jobs;
create trigger email_jobs_touch_updated_at
before update on public.email_jobs
for each row execute function public.touch_updated_at();

create or replace function public.sync_leads_identity()
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  next_value bigint;
begin
  select coalesce(max(id), 0) + 1 into next_value from public.leads;
  perform setval(
    pg_get_serial_sequence('public.leads', 'id'),
    greatest(next_value, 1),
    false
  );
  return next_value;
end;
$$;

create or replace function public.claim_next_email_job(worker_id text)
returns setof public.email_jobs
language plpgsql
security invoker
set search_path = ''
as $$
begin
  return query
  with candidate as (
    select job.id
    from public.email_jobs as job
    where job.status in ('pending', 'failed')
      and job.available_at <= now()
      and (
        job.locked_at is null
        or job.locked_at < now() - interval '15 minutes'
      )
    order by job.available_at, job.created_at
    for update skip locked
    limit 1
  )
  update public.email_jobs as job
  set
    status = 'processing',
    locked_at = now(),
    locked_by = worker_id,
    attempts = job.attempts + 1
  from candidate
  where job.id = candidate.id
  returning job.*;
end;
$$;

insert into public.campaigns (id)
values (1)
on conflict (id) do nothing;

alter table public.campaigns enable row level security;
alter table public.leads enable row level security;
alter table public.active_clients enable row level security;
alter table public.events enable row level security;
alter table public.processed_imap_uids enable row level security;
alter table public.email_jobs enable row level security;

revoke all on table public.campaigns from anon, authenticated;
revoke all on table public.leads from anon, authenticated;
revoke all on table public.active_clients from anon, authenticated;
revoke all on table public.events from anon, authenticated;
revoke all on table public.processed_imap_uids from anon, authenticated;
revoke all on table public.email_jobs from anon, authenticated;
revoke execute on function public.touch_updated_at() from public, anon, authenticated;
revoke execute on function public.sync_leads_identity() from public, anon, authenticated;
revoke execute on function public.claim_next_email_job(text) from public, anon, authenticated;

grant select, insert, update, delete on table public.campaigns to service_role;
grant select, insert, update, delete on table public.leads to service_role;
grant select, insert, update, delete on table public.active_clients to service_role;
grant select, insert, update, delete on table public.events to service_role;
grant select, insert, update, delete on table public.processed_imap_uids to service_role;
grant select, insert, update, delete on table public.email_jobs to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.sync_leads_identity() to service_role;
grant execute on function public.claim_next_email_job(text) to service_role;

commit;
